development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:0f73d14317983678d8b8124ffead0dc9@pike.redistogo.com:9981/
  channel_prefix: message_app_production
